### ISSUE TITLE
Generic CSRF Policy blocks same-site requests

### ISSUE THREAD

**Issue by relnetops** [binbashar/terraform-aws-waf-owasp#15]
The generic CSRF policy should be updated to allow requests that have the `sec-fetch-site` [(MDN)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site) header with a value of `same-site` or `same-origin`.  Otherwise, it blocks the request that does not have, and does not need, a CSRF token.

**Comment by exequielrafaela** [comment]
@relnetops Thanks for reporting this issue. We hope yo work it out during 2020 Q3. 

CC: @diego-ojeda-binbash

**Comment by joekhoobyar** [comment]
I actually need this for my use cases as well, I am planning on implementing it today, and sending a PR.

**Comment by binbashdevops** [comment]
@joekhoobyar It sounds great, thanks for all your collab here :handshake: :100: 

CC: @diego-ojeda-binbash @exequielrafaela

**Comment by relnetops** [comment]
@exequielrafaela @joekhoobyar Thank you for addressing this!  However, when I tried to update my WAF, I get this error:

```
Error: Error deleting ByteMatchSet: WAFReferencedItemException: This entity is still referenced by other entities.
```

**Comment by exequielrafaela** [comment]
@relnetops Probably recreating from scratch could help here, have your already tried this? Consider the associations to ALBs, CloudFront, etc should be fully as code referencing to the resources create but this module -> module.name.resource | data sources | outputs , after recreating your resources with the module (destroy / apply), make sure to re-run (apply) the code we're the module data sources | outputs are being used.

CC: @diego-ojeda-binbash

**Comment by relnetops** [comment]
@exequielrafaela Everything is automated in TF.  Destroying every environment is not possible as it would impact business continuity.

**Comment by exequielrafaela** [comment]
> @exequielrafaela Everything is automated in TF. Destroying every environment is not possible.

@relnetops I mean just (strictly) recreating tf-owasp-module resources (should ideally be isolated at tf-state level to avoid affecting other resources, or you can still use `-target=resource` -> A Resource Address to target. For more information, see the targeting docs from terraform plan.) and then if necessary re-applying at your others resources like (plan -> apply) CF.

**Comment by relnetops** [comment]
@exequielrafaela It looks like the problem is with `module.<foo>.aws_wafregional_byte_match_set.match_csrf_method` in that it needs to be disassociated from the Rule before it can be deleted.

**Comment by exequielrafaela** [comment]
@relnetops That looks right considering the output ERROR -> `This entity is still referenced by other entities.` Are you going to try removing it from the Web Console and re-try the `terraform apply`. Please let us know how it goes.

**Comment by relnetops** [comment]
@exequielrafaela Yes, manually removing the Filter from the Rule allows the Filter to be deleted by TF.  I'd rather not need to do this manually, though.

**Comment by exequielrafaela** [comment]
@relnetops we're glad to hear to could solve it. I understand your concern here, it seems a `terraform-aws-provider` limitation though. I don't think this miss behavior could be addressed from the module logics side. @diego-ojeda-binbash OJ we'll wait for your feedback here, thanks in advance.

CC: @binbashar/leverage-ref-architecture-aws-admin

**Comment by diego-ojeda-binbash** [comment]
@relnetops @exequielrafaela Sorry for joining late to this conversation. It's great that you managed to work around the issue.
The only thing I can think of is: how about using `terraform taint` to force the destroying and recreation of the affected module's resources? I mean, as an alternative to destroying and recreating the entire module's resources.

**Comment by relnetops** [comment]
@diego-ojeda-binbash Tainting didn't work.  It's still the same error.

I agree that it's more of a TF issue than a module issue.  Thanks for all your help! @exequielrafaela

**Comment by exequielrafaela** [comment]
@relnetops Thanks for your collab and feedback here too :heavy_check_mark: We keep in touch :handshake:
