### ISSUE TITLE
CSRF checks should protect against more than just POST methods

### ISSUE THREAD

**Issue by joekhoobyar** [binbashar/terraform-aws-waf-owasp#22]
## Describe the Feature

CSRF checks should protect against more than just POST methods

- Pedantically speaking, only the methods `GET`, `HEAD` and `OPTIONS` should be excluded from the checks.
- Practically speaking, most browsers will only send `POST`, and AJAX will add `PUT`, `DELETE`, and `PATCH`.

## Expected Behavior

Support input variables that allow users to customize the following:

- CSRF methods to exclude from the check.  This would allow negative matches for `GET`, `HEAD`, and `OPTIONS` by default.
- CSRF methods to include in the check.  This would allow positive matches for `POST`, `PUT`, `DELETE` and `PATCH`.

## Use Case

The goal is to improve the CSRF protection to protect more than just `POST` requests.

## Describe Ideal Solution

- A negative match based on an input variable:  `csrf_exclude_methods` defaulting to `["get", "head", "options"]`.
- An "opt in" positive match based on an input variable `csrf_include_methods` defaulting to `[]`.

## Alternatives Considered

Optionally, we could retain existing behavior by making `csrf_exclude_methods` opt-in, and defaulting `csrf_include_methods` to `["post"]`.  But I'm not sure what the value would be in that.

## Additional Context

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

**Comment by joekhoobyar** [comment]
FYI @binbashdevops , I plan on implementing a PR for this today as well.

**Comment by exequielrafaela** [comment]
@joekhoobyar the feature request issue looks great. Thanks for all your lately collaboration :muscle: :100: We'll wait for @binbashar/leverage-project-docker-admin members review and hope to merge and release it in few hours :crossed_fingers: . Keep you posted!!!
