### ISSUE TITLE
Typo in Dynamic Variable

### ISSUE THREAD

**Issue by mangomagic** [binbashar/terraform-aws-waf-owasp#3]
https://github.com/binbashar/terraform-aws-waf-owasp/blob/75c1f19d7d915d19b4de5b77b2b9913460ea9754/modules/waf-regional/wafregional_ruleset5_admin_access.tf#L50

The line:

`value = ip_set_descriptors.value`

should be

`value = ip_set_descriptor.value`

A fix would be nice :-)

**Comment by exequielrafaela** [comment]
@mangomagic thanks for the heads up here! 

You're absolutely right -> https://www.terraform.io/docs/providers/aws/r/wafregional_ipset.html

Will fix this in our next release.
We'll keep you updated :handshake:

**Comment by exequielrafaela** [comment]
@mangomagic sorry for taking some more time thank expected, PR: https://github.com/binbashar/terraform-aws-waf-owasp/pull/4 will fix the issue and also adding some useful alb list association feature :)  

Merged ans solved -> https://github.com/binbashar/terraform-aws-waf-owasp/releases/tag/v1.0.2 :handshake: :checkered_flag:

**Comment by lucasvinals** [comment]
Hi all, the same happens in **wafregional_ruleset10_blacklisted_ips** 

I would be very grateful if it could be solved.

Thanks

**Comment by exequielrafaela** [comment]
@lucasvinals we'll check it as soons as possible. Thanks for your collab here! :handshake:

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/terraform-aws-waf-owasp/pull/6
