### ISSUE TITLE
API Gateway Stage usage

### ISSUE THREAD

**Issue by imroot2202** [binbashar/terraform-aws-waf-owasp#32]
## Describe the Feature

I would like to use your module for API Gateway

## Expected Behavior

The same as for ALB

## Use Case
I was trying to attach WAF to gateway stage, but didn't find how to do it.

**Comment by exequielrafaela** [comment]
@lgallard Consider that the alb_arn variable is actually a definition of a waf association, that can support ALB, APIGW, and any other support WAF v1 AWS service or resource. 

That being said, to address this issue, we'll need to:

- Rename the resources of the module to explicitly present this association possibility.
- Properly update the documentation
   - terraform-docs
   - Add a consideration section explaining that this new release will change the state resources name which will imply tf trying to re create those resources. If you have a pinned version of the module this could be updated in a controlled manner. Or consider using the binbash `leverage tfautomove` command, and in case you're using plan terraform cli follow: https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config#rename-and-move-a-resource

**Comment by exequielrafaela** [comment]
Covered at https://github.com/binbashar/terraform-aws-waf-owasp/pull/36
